/* eslint-disable no-param-reassign */
import { ExportToCsv } from 'export-to-csv';
import { flattenObject } from 'utils';
import { users as iUsers } from '.prisma/client';

const generateCSV = (data: iUsers[]) => {
  const options = {
    fieldSeparator: ',',
    quoteStrings: '"',
    decimalSeparator: '.',
    showLabels: true,
    showTitle: true,
    title: `This file was generated by Sign Me In on ${new Date().toLocaleString()}`,
    useTextFile: false,
    useBom: true,
    useKeysAsHeaders: true,
    filename: `Sign_Me_In_${new Date().toLocaleDateString()}`,
  };
  const csvExporter = new ExportToCsv(options);
  const flattened = data.map(user => flattenObject(user));
  const formatted = formatUsersForDownload(data);
  return csvExporter.generateCsv(formatted);
};

// Format data to rename First/Last name and remove display_name
const formatUsersForDownload = (users: iUsers[]) => {
  const formatted = users.map(user => {
    const newUser = {
      'First Name': user.first_name,
      'Last Name': user.last_name,
      ...user,
    };

    delete newUser.first_name;
    delete newUser.last_name;
    delete newUser.id;
    delete newUser.created_at;

    return flattenObject(newUser);
  });
  return formatted;
};
export default generateCSV;
