/* eslint-disable no-param-reassign */
import { ExportToCsv } from 'export-to-csv';

const generateCSV = data => {
  const options = {
    fieldSeparator: ',',
    quoteStrings: '"',
    decimalSeparator: '.',
    showLabels: true,
    showTitle: true,
    title: `This file was generated by Sign Me In on ${new Date().toLocaleString()}`,
    useTextFile: false,
    useBom: true,
    useKeysAsHeaders: true,
    filename: `Sign_Me_In_${new Date().toLocaleDateString()}`,
  };
  const csvExporter = new ExportToCsv(options);
  const formatted = formatData(data);
  return csvExporter.generateCsv(formatted);
};

// Format data to rename First/Last name and remove display_name
const formatData = data => {
  const formatted = data.map(obj => {
    const newObj = {
      'First Name': obj.first_name,
      'Last Name': obj.last_name,
      ...obj,
    };
    delete newObj.first_name;
    delete newObj.last_name;
    delete newObj.display_name;
    return newObj;
  });
  return formatted;
};
export default generateCSV;
